### ISSUE TITLE
rails sass helper asset_path doesn't include hash, need to use asset_url (or image_url)

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow-certification#138]
ActionController::RoutingError (No route matches [GET] "/assets/arrow-down.svg"):

I'm guessing this is the same bug as the old one, needs an asset-path call

**Comment by orischwartz** [comment]
See also https://github.com/department-of-veterans-affairs/caseflow/pull/601

**Comment by orischwartz** [comment]
This actually sounds like the assets aren't precompiled for production...it's in the [deployment script](https://github.com/department-of-veterans-affairs/deployment/blob/47eee5cedc533a4af6e3da2444c10b1f9c3fdb8a/playbooks/caseflow.yml#L157) but maybe was skipped due to all the manual changes lately?
