### ISSUE TITLE
Add PostgresDB

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-certification#314]
- [x] Figure out the database strategy
- [x] Add `POSTGRES_URL` to deploy scripts

**Comment by shanear** [comment]
Did some early research and testing on the 2 database rails setup. It turns out to be really easy, so I'm going to close this until we have a concrete use case for PostgresDB (which we probably do somewhere in the backlog).

**Comment by cmgiven** [comment]
Chris and Shane to sync up on what's needed in PM/725.

**Comment by cmgiven** [comment]
So the conclusion of the conversation we had at the end of last week:

* We need to track a certification record that has 1) timestamps for when the certification was first viewed, 2) timestamps for when each of the expected documents was found (which would be equal to timestamp (1) if they were present when first viewed), and 3) a timestamp for when the appeal was certified.
* In addition, we'll track changes to the form by storing a JSON blob of its contents after each save.

After continuing to mull on this one, realize that we also need a way of tracking each time the appeal is viewed. Perhaps this calls for an "event" record? And we'll need to be able to track who's doing the viewing (and would be nice to know who certified the appeal as well), which points toward having a user record.

@shanear: This track for you?

**Comment by shanear** [comment]
@cmgiven yeah, I think each of these should be tracked in separate issues though. I can do those and start coding them.

**Comment by cmgiven** [comment]
Just documenting our conversation, there isn't anything that logically qualifies as a "view," so instead will use "Appeals Started" and "Appeals Certified," those first and last timestamps. This is what we needed for the rates, in any case, and just slightly tweaks what the top row of the dashboard looks like.

**Comment by shanear** [comment]
@orischwartz Should we create a new database, or reuse the efolder-caseflow database (setting the precedent that all Caseflow apps will share the same DB)?

Here are my thoughts so far:

## Pros (new database):
 - eFolder Express and Caseflow Certification don't share any of the same data. Doesn't make sense to share databases right now.
- One less single point of failure for eFolder Express and Certification. 
- These databases are so far from replacing VACOLS, or even trying to, to consider that as a reason for sharing databases.
- More DBs = more I/O
- We can always merge DBs later if that's something we want to do.

## Pros (share database):
- less RDS instances to keep track of.
- lower cost.
- start the pattern of replacing VACOLS, creating one CaseflowDB.

I think I'm leaning towards the new DB. What are your thoughts?

**Comment by cmgiven** [comment]
Agree that new DB makes the most sense for this specific case (eFolder/Certification), particularly given the complete data incongruency. I think that calculus flips when considering, say, Certification/Activation, where overlap is much more obvious and sharing adds quite a bit of utility. Given that, I think we'll probably be starting "CaseflowDB" sooner rather than later, but I don't think that particularly affects whether these two should be in the same or different databases.

**Comment by orischwartz** [comment]
The right thing to do is create separate infrastructure for each application: separate memcached cluster, database instance, etc.  Ordinarily, it's a no-brainer. But our database is lightly used ad we're over-provisioned for each app. 

Our production instances cost $308.48/month = 3,701.76 US$/year, which isn't enough to sway the decision. 

From the application's point-of-view it won't matter. And because the dataset is tiny we can always change our mind and migrate if needed. 

So I also vote separate instances.

**Comment by shanear** [comment]
This is donesies. Deployed this morning.

**Comment by orischwartz** [comment]
FYI @askldjd
