### ISSUE TITLE
Caseworker Landing View

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow-certification#388]
As an AMC Caseworker,
when I visit `/dispatch`,
then i should see a button "Create End Product"

when I click that button,
then it should assign the oldest case that needs to be processed to me
and i should be redirected to a page relating to that case (to be completed in a future story)

**Comment by joofsh** [comment]
Question based on the designs linked in [this related ticket](https://github.com/department-of-veterans-affairs/caseflow-certification/issues/389) (Designs look great!)

It sounds like the task is not being assigned to the employee until they click "Create End Product", correct? This is somewhat problematic since we are showing "Next Appeal" but not actually assigning it to the user yet. 

Imagine 2 employees load the page around the same time (both showing the same next unassigned appeal). Whoever clicks first gets the task they were currently seeing appeal information about. The 2nd employee who clicks would 1) get an error or 2) we could automatically assign them the _next_ unassigned task.

**Comment by shanear** [comment]
Haha, we pointed this out too. This story is only for the button, not anything else. It's possible that we cut the "Next Appeal" part for exactly that reason.
